### ISSUE TITLE
Keyword problem

### ISSUE THREAD

**Issue by jojorne** [dfl/comfyui-clip-with-break#1]
So, it turns out that "BREAK" doesn't work. It's not that it doesn't work. It's just that A1111 does it differently.
If you have "A\n BREAK \nB", you'll end up with a list like "A\n, \nB".

```python
import re

text = "A\n BREAK \nB"

list = text.split(" BREAK ") # [ "A\n", "\nB" ]

re_break = re.compile(r"\s*\bBREAK\b\s*", re.S)
re_list = re.split(re_break, text) # [ "A", "B" ]
```

**Comment by dfl** [comment]
Hi, thanks for pointing this out... looks like an easy fix:
`prompts = re.split(r"\s*\bBREAK\b\s*", text)`

I just cobbled this idea together last night, it was working when I edited the base /ComfyUI/nodes.py manually, but I'm still having problems getting the custom node working (it loads fine by the javascript but the UI is freezing)
